import type { Product } from "@/types";

/** Catálogo base del menú (ids alineados con mock-data / portal). */
export const defaultCatalog: Product[] = [
  {
    id: "p1",
    name: "Amnesia Haze",
    category: "FLOR",
    sku: "FL-AMN",
    stock: 124,
    unit: "g",
    lowStockThreshold: 50,
    pricePerUnit: 9,
    batch: "L-2605",
    expiresAt: "2026-11-01",
  },
  {
    id: "p2",
    name: "Critical Kush",
    category: "FLOR",
    sku: "FL-CRK",
    stock: 38,
    unit: "g",
    lowStockThreshold: 50,
    pricePerUnit: 10,
    batch: "L-2604",
    expiresAt: "2026-10-15",
  },
  {
    id: "p3",
    name: "Hash Marroquí",
    category: "EXTRACTO",
    sku: "EX-HMR",
    stock: 76,
    unit: "g",
    lowStockThreshold: 30,
    pricePerUnit: 12,
    batch: "L-2588",
    expiresAt: "2027-01-20",
  },
  {
    id: "p4",
    name: "Gominolas CBD",
    category: "COMESTIBLE",
    sku: "CM-GMC",
    stock: 9,
    unit: "ud",
    lowStockThreshold: 15,
    pricePerUnit: 6,
    batch: "L-2602",
    expiresAt: "2026-08-30",
  },
  {
    id: "p6",
    name: "Limonada CBD",
    category: "COMESTIBLE",
    sku: "CM-LIM",
    stock: 24,
    unit: "ud",
    lowStockThreshold: 10,
    pricePerUnit: 4.5,
    batch: "L-2606",
    expiresAt: "2026-09-15",
  },
  {
    id: "p5",
    name: "Camiseta Verda",
    category: "MERCH",
    sku: "MR-TSH",
    stock: 60,
    unit: "ud",
    lowStockThreshold: 10,
    pricePerUnit: 18,
    batch: "—",
    expiresAt: null,
  },
];
